### ISSUE TITLE
Can't pull image for version 1.0-1 from default registry 

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-scikit-learn-container#114]
I wanted to use the new image that supports Python 3.9 and the first stable scikit learn release: I went to 
https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-docker-containers-scikit-learn-spark.html and constructed the repo URL for eu-central-1.
```
REPO="492215442770.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-scikit-learn"

 # works
VERSION="0.23-1"
docker pull ${REPO}:${VERSION}-cpu-py3
# fetches image ... 

# does not work
VERSION="1.0-1"
docker pull ${REPO}:${VERSION}-cpu-py3
Error response from daemon: manifest for 492215442770.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-scikit-learn:1.0-1-cpu-py3 not found: manifest unknown: Requested image not found
```

I am afraid the image was never built? Also, with the latest sagemaker SDK (sagemaker-2.88.3), only previous versions seem to be available: 
```
(invocation command)
2022-05-09 12:00:08,924 - sagemaker.image_uris - INFO - Same images used for training and inference. Defaulting to image scope: inference.
Traceback (most recent call last):
  File "/Users/lorenz/git/signals/sagemaker/o2-fit-model.py", line 63, in <module>
    model = SKLearn(
  File "/Users/lorenz/git/signals/.venv/lib/python3.9/site-packages/sagemaker/sklearn/estimator.py", line 149, in __init__
    self.image_uri = image_uris.retrieve(
  File "/Users/lorenz/git/signals/.venv/lib/python3.9/site-packages/sagemaker/image_uris.py", line 147, in retrieve
    version = _validate_version_and_set_if_needed(version, config, framework)
  File "/Users/lorenz/git/signals/.venv/lib/python3.9/site-packages/sagemaker/image_uris.py", line 319, in _validate_version_and_set_if_needed
    _validate_arg(version, available_versions + aliased_versions, "{} version".format(framework))
  File "/Users/lorenz/git/signals/.venv/lib/python3.9/site-packages/sagemaker/image_uris.py", line 432, in _validate_arg
    raise ValueError(
ValueError: Unsupported sklearn version: 1.0-1. You may need to upgrade your SDK version (pip install -U sagemaker) for newer sklearn versions. Supported sklearn version(s): 0.20.0, 0.23-1.
```

**Comment by lorenzwalthert** [comment]
Seems to work now. Probably just took some time to deploy...
