### ISSUE TITLE
Error sagemaker_containers._errors.InstallModuleError: InstallModuleError:  (scikit-learn container 0.23-1)

### ISSUE THREAD

**Issue by sarojdongol** [aws/sagemaker-scikit-learn-container#57]
I am using scikit-learn-container 0.23-1, but recently I started seeing the following error.   Can you please help to resolve this issue.

ERROR: Command errored out with exit status 1:
     command: /miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/model-server/tmp/pip-req-build-crhgwcrr/setup.py'"'"'; __file__='"'"'/home/model-server/tmp/pip-req-build-crhgwcrr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /home/model-server/tmp/pip-req-build-crhgwcrr/pip-egg-info
         cwd: /home/model-server/tmp/pip-req-build-crhgwcrr/
    Complete output (3 lines):
    WARNING: '' not a valid package name; please use only .-separated package names in setup.py
    running egg_info
    error: Invalid distribution name or version syntax: .-train-1.0.0
    ----------------------------------------
2020/09/19 05:45:50 [crit] 18#18: *11 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080"

15:46:02
2020/09/19 05:45:50 [crit] 18#18: *13 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080"
2020/09/19 05:45:50 [crit] 18#18: *13 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 169.254.255.130, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "169.254.255.131:8080"


Traceback (most recent call last): File "/miniconda3/bin/serve", line 8, in <module> sys.exit(serving_entrypoint()) File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 146, in serving_entrypoint server.start(env.ServingEnv().framework_module) File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_server.py", line 86, in start _
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 146, in serving_entrypoint
    server.start(env.ServingEnv().framework_module)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_server.py", line 86, in start
    _modules.import_module(env.module_dir, env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 256, in import_module
    install(_env.code_dir)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 119, in install
    shlex.split(cmd), _errors.InstallModuleError, cwd=path, capture_error=capture_error
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_process.py", line 50, in check_error
    raise error_class(return_code=return_code, cmd=" ".join(cmd), output=stderr)

15:46:02
sagemaker_containers._errors.InstallModuleError: InstallModuleError:
sagemaker_containers._errors.InstallModuleError: InstallModuleError:

**Comment by sarojdongol** [comment]
Note:  training get successful but only inference throwing the error,

**Comment by sarojdongol** [comment]
Closing the issue
