### ISSUE TITLE
py3.6 support for SageMaker SDK -> CoreML conversion issue

### ISSUE THREAD

**Issue by niakki** [aws/sagemaker-scikit-learn-container#8]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Sci-kit Learn / Logistic Regression
- **Framework Version**: 0.20
- **Python Version**: 3.5
- **CPU or GPU**: CPU
- **Python SDK Version**: SageMaker SDK on py3.5 
- **Are you using a custom image**: No

### Describe the problem
Created a training job using SageMaker SDK's SKlearn model wrapper, extra hook added for converting *.joblib (pickled) sklearn files to Apple's CoreML (*.mlmodel) format in train.py. However, running the code on SageMaker training job instance gives an error.

### Minimal repro / logs
[13/Dec/2018 07:49:49] INFO - Converting SKLearn model to CoreML
07:49:49
[ERROR] Currently "One Vs Rest" is the only supported multiclass option.
07:49:49
Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/opt/ml/code/train.py", line 68, in <module> model_uri_http = coreml_converter(model, bucketName) File "/opt/ml/code/util.py", line 34, in coreml_converter mlmode
07:49:49
TypeError: Expected model to be a .mlmodel file or a Model_pb2 object

this issue is with Python3.5, I have checked it on my local (Py3.6 works just fine)

**Comment by ericaws** [comment]
Hello,

We don't have any short term plans to release a new image. As @ChoiByungWook commented, it may be quicker to build your own sklearn image using python 3.6 for now.

Thank you!
