### ISSUE TITLE
SageMaker endpoint creation fails with: The primary container for production variant my-endpoint-scikit did not pass the ping health check

### ISSUE THREAD

**Issue by betonetotbo** [aws/sagemaker-scikit-learn-container#82]
I have built this image (final version) and pulled to my ECR.

I created a multi-model using this ECR image, and a enpoint configuration pointing to it.

But when I create the endpoint it fails with:

`The primary container for production variant my-endpoint-scikit did not pass the ping health check. Please check CloudWatch logs for this endpoint.`

This is my cloudwatch logs:

```

2021-08-16 12:02:39,916 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:02:39,916 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:02:39,916 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=f3b696887c8d9b6e1caab0cab225433724865339c0b4a74f82b3077fde0670bc
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-4k4e1ai3/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
2021-08-16 12:02:51,107 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
2021-08-16 12:02:51,110 INFO - sagemaker-containers - Module None does not provide a setup.py. 
Generating setup.py
2021-08-16 12:02:51,110 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:02:51,110 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:02:51,110 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=aaf268e371c01bcfacc89df5e01f575c1f2c1e154f71b3514ec1c20ddbc507bc
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-gofg4ypl/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
2021-08-16 12:03:01,780 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
2021-08-16 12:03:01,782 INFO - sagemaker-containers - Module None does not provide a setup.py. 
Generating setup.py
2021-08-16 12:03:01,782 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:03:01,783 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:03:01,783 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=145d83442661b130e6a73e755ee416bb30768c2659d7e9352feceac4e04934c1
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-86_b9eye/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
2021-08-16 12:03:12,746 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
2021-08-16 12:03:12,749 INFO - sagemaker-containers - Module None does not provide a setup.py. 
Generating setup.py
2021-08-16 12:03:12,749 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:03:12,749 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:03:12,749 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=4971ef06184c003b3764ce7c8619faed5c62560a02d3807799a1677a44d13992
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-_xt4f4_h/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
2021-08-16 12:03:21,874 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
2021-08-16 12:03:21,876 INFO - sagemaker-containers - Module None does not provide a setup.py. 
Generating setup.py
2021-08-16 12:03:21,876 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:03:21,876 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:03:21,877 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=c97123b5d885ab818091fae932c3ba1a11ef4d07ca98d8ba495dc5d49f613660
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-vckk4yg7/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
2021-08-16 12:03:32,937 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
2021-08-16 12:03:32,939 INFO - sagemaker-containers - Module None does not provide a setup.py. 
Generating setup.py
2021-08-16 12:03:32,939 INFO - sagemaker-containers - Generating setup.cfg
2021-08-16 12:03:32,939 INFO - sagemaker-containers - Generating MANIFEST.in
2021-08-16 12:03:32,939 INFO - sagemaker-containers - Installing module with the following command:
/miniconda3/bin/python -m pip install . 
Processing /opt/ml/code
Building wheels for collected packages: None
  Building wheel for None (setup.py): started
  Building wheel for None (setup.py): finished with status 'done'
  Created wheel for None: filename=None-1.0.0-py2.py3-none-any.whl size=2432 sha256=6761fc5c262da36a22fa4354b4e22f6d256a2dc213c1c38dd60b9d36f842e22b
  Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-1574wt1f/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
Successfully built None
Installing collected packages: None
Successfully installed None-1.0.0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/bin/serve", line 8, in <module>
    sys.exit(serving_entrypoint())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 144, in serving_entrypoint
    start_model_server()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving_mms.py", line 124, in start_model_server
    modules.import_module(serving_env.module_dir, serving_env.module_name)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 263, in import_module
    six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_modules.py", line 258, in import_module
    module = importlib.import_module(name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
sagemaker_containers._errors.ImportModuleError: 'NoneType' object has no attribute 'startswith'
```

**Comment by betonetotbo** [comment]
I finally discovered...

When I want to use the multi-model server mode, I need to define in the sagemaker model this ENV vars:
- SAGEMAKER_SUBMIT_DIRECTORY = pointing to a .tar.gz file (S3 uri) container a python script inside
- SAGEMAKER_PROGRAM = the name of the python script, who needs to have a `def model_fn(model_dir)` function defined 

When the MMS starts it will import this file and use this `model_fn` when then endpoint is invoked for perform a prediction.

This is a little tricky, because the training job also need this configuration (to run the train script), but required inside the `hyperparameters` and the case-sensitive here is the trick: `sagemaker_submit_directory` and `sagemaker_program`.
